name: build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grand Permissions
        run: chmod +x gradlew

      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Print NodeJS Version
        run: node -v

      - name: print NPM Version
        run: npm -v

      - name: Install Style-Dictionary
        run: npm install -g style-dictionary

      - name: Check Existing APK
        run: |
          APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
          
          if [ -f "$APK_PATH" ]; then
            echo "APK Exist ---------------------------------------------------------------"
          else
            echo "APK is not Exist---------------------------------------------------------------"
          fi

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Check Existing APK
        run: |
          APK_PATH="app/build/outputs/apk/debug/app-debug.apk"

          if [ -f "$APK_PATH" ]; then
            echo "APK Exist ---------------------------------------------------------------"
          else
            echo "APK is not Exist ---------------------------------------------------------------"
          fi